name: dio_cache_interceptor_sembast_store
description: A DB cache store implementation with Sembast for dio_cache_interceptor package.
version: 1.1.0
homepage: https://github.com/xavier-lyu/dio_cache_interceptor_sembast_store

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  dio: ^4.0.6
  dio_cache_interceptor: ^3.3.0
  sembast: ^3.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
